
-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.


CREATE TABLE Users (
   id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   email VARCHAR UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL,
   firstname VARCHAR(255) NOT NULL,
   lastname VARCHAR(255) NOT NULL,
   displayname VARCHAR(255) NOT NULL,
   useraddress VARCHAR(255),
   balance DECIMAL(12, 2) DEFAULT 0.00,
   accountnumber INT UNIQUE NOT NULL,
   summary VARCHAR(255)
);


CREATE TABLE Sellers (
   seller_id INT PRIMARY KEY,
   rating DECIMAL(3, 2) DEFAULT 0.0,
   FOREIGN KEY (seller_id) REFERENCES Users(id)
)


CREATE TABLE Products (
   id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(255) UNIQUE NOT NULL,
   price DECIMAL(12,2) NOT NULL,
   seller_id INT NOT NULL,
   category_id INT NOT NULL,
   summary VARCHAR(255) NOT NULL,
   available BOOLEAN DEFAULT TRUE,
   created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
   FOREIGN KEY (seller_id) REFERENCES Sellers(seller_id),
   FOREIGN KEY (category_id) REFERENCES Categories(category_id)
);


CREATE TABLE Categories (
   category_id INT NOT NULL PRIMARY KEY,
   category_name VARCHAR(255) NOT NULL,
   parent_id INT,
   FOREIGN KEY parent_id REFERENCES Categories(category_id)
);




CREATE TABLE Purchases (
   id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   uid INT NOT NULL REFERENCES Users(id),
   pid INT NOT NULL REFERENCES Products(id),
   time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);


