-- Create Users table with updated schema
CREATE TABLE Users (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    address TEXT,
    password VARCHAR(255) NOT NULL,
    balance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    account_number VARCHAR(36) UNIQUE NOT NULL,
    public_name VARCHAR(255) NOT NULL,
    is_seller BOOLEAN NOT NULL DEFAULT FALSE,
    summary TEXT
);

-- Create Categories table with hierarchical structure
CREATE TABLE Categories (
    category_id SERIAL PRIMARY KEY,
    category_name VARCHAR(255) UNIQUE NOT NULL,
    parent_id INT REFERENCES Categories(category_id) ON DELETE SET NULL -- Hierarchical structure
);

-- Create Products table, as it depends on Categories and Users
CREATE TABLE Products (
    product_id SERIAL PRIMARY KEY,
    seller_id INT NOT NULL REFERENCES Users(user_id),  -- References Users table
    category_id INT REFERENCES Categories(category_id),  -- References Categories table
    name VARCHAR(255) UNIQUE NOT NULL,
    summary TEXT NOT NULL,
    image_url TEXT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    available BOOLEAN DEFAULT TRUE  -- Add available column
);


-- Create Product_Categories table (many-to-many relationship)
CREATE TABLE Product_Categories (
    product_id INT NOT NULL REFERENCES Products(product_id),
    category_id INT NOT NULL REFERENCES Categories(category_id),
    PRIMARY KEY (product_id, category_id)
);

-- Create Purchases table, as it depends on Products and Users
CREATE TABLE Purchases (
    purchase_id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(user_id),  -- References Users table
    product_id INT NOT NULL REFERENCES Products(product_id),  -- References Products table
    time_purchased TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);
